default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mybasecamp2_development
  host: localhost
  username: postgres
  password: B1983ball#

test:
  <<: *default
  database: mybasecamp2_test
  host: localhost
  username: postgres
  password: B1983ball#

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

